"""Persist the statistical board's report (Markdown + PDF) and a full audit
transcript (JSON) of the debate."""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import report as report_mod


@dataclass
class RoundRecord:
    number: int
    analyst_notes: str
    analyst_tool_calls: list[dict[str, Any]]
    frequentist: str
    assumptions: str
    bayesian: str
    verification: str
    judge_rationale: str
    decision: str
    next_instructions: str
    draft: str


@dataclass
class Transcript:
    question: str
    model: str
    started_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    hypothesis: str = ""
    key_questions: list[str] = field(default_factory=list)
    rounds: list[RoundRecord] = field(default_factory=list)
    final_report: str = ""
    # Dataset context, so the report can render its figures/tables appendix.
    data_path: str = ""
    group_col: str | None = None
    value_col: str | None = None
    alpha: float = 0.05


def _slug(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return (slug[:60] or "report").rstrip("-")


def save(transcript: Transcript, out_dir: str | Path) -> dict[str, Path]:
    """Write the Markdown report, render it to PDF, and dump the JSON transcript.
    Returns {'pdf', 'md', 'json'} paths."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    base = f"{_slug(transcript.question)}-{stamp}"

    md_path = out / f"{base}.md"
    md_path.write_text(_render_report(transcript), encoding="utf-8")

    pdf_path = out / f"{base}.pdf"
    report_mod.convert_file(
        md_path, pdf_path,
        data_path=transcript.data_path or None,
        group_col=transcript.group_col, value_col=transcript.value_col,
        alpha=transcript.alpha)

    json_path = out / f"{base}.transcript.json"
    json_path.write_text(json.dumps(asdict(transcript), indent=2, ensure_ascii=False),
                         encoding="utf-8")

    return {"pdf": pdf_path, "md": md_path, "json": json_path}


def _render_report(t: Transcript) -> str:
    body = t.final_report.strip()
    footer = (f"\n\n---\n\n*Generated by the statistical board over {len(t.rounds)} "
              f"round(s) on model `{t.model}`. Every statistic was computed and "
              f"independently reproduced with the stat_board engine.*")
    return body + footer + "\n"
