from __future__ import annotations

import json

import pandas as pd
import pytest

from stat_board import prep

# --------------------------------------------------------------------------- #
# profile()
# --------------------------------------------------------------------------- #

def test_profile_detects_preamble_rows(tmp_path):
    p = tmp_path / "banner.csv"
    p.write_text(
        "Export generated by ACME,,\n"
        "Confidential,,\n"
        "id,group,value\n"
        "1,A,10\n2,A,11\n3,B,12\n4,B,13\n"
    )
    prof = prep.profile(p)
    assert prof["read"]["skiprows"] == 2
    assert any("preamble" in n for n in prof["notes"])


def test_profile_flags_numeric_as_text_column(tmp_path):
    p = tmp_path / "money.csv"
    p.write_text("id,amount\n1,\"$1,200\"\n2,\"$1,400\"\n3,\"$1,100\"\n4,\"$1,900\"\n")
    prof = prep.profile(p)
    assert "numeric_as_text:coerce" in prof["columns"]["amount"]["flags"]


def test_profile_flags_high_skew_numeric_column(tmp_path):
    p = tmp_path / "skewed.csv"
    values = [1, 1, 1, 1, 1, 1, 1, 2, 3, 500]
    p.write_text("v\n" + "\n".join(str(v) for v in values) + "\n")
    prof = prep.profile(p)
    flags = prof["columns"]["v"]["flags"]
    assert any(f.startswith("high_skew") for f in flags)


def test_profile_flags_datelike_column(tmp_path):
    p = tmp_path / "dates.csv"
    p.write_text("event_date,value\n2020-01-01,1\n2020-02-01,2\n2020-03-01,3\n2020-04-01,4\n")
    prof = prep.profile(p)
    assert "date:parse->year/decade" in prof["columns"]["event_date"]["flags"]


def test_profile_missing_file_raises(tmp_path):
    with pytest.raises(ValueError, match="file not found"):
        prep.profile(tmp_path / "nope.csv")


def test_profile_counts_duplicate_rows(tmp_path):
    p = tmp_path / "dupes.csv"
    p.write_text("a,b\n1,2\n1,2\n3,4\n")
    prof = prep.profile(p)
    assert prof["n_duplicate_rows"] == 1


# --------------------------------------------------------------------------- #
# suggest_recipe()
# --------------------------------------------------------------------------- #

def test_suggest_recipe_proposes_coerce_for_numeric_as_text(tmp_path):
    p = tmp_path / "money.csv"
    p.write_text("id,amount\n1,\"$1,200\"\n2,\"$1,400\"\n3,\"$1,100\"\n4,\"$1,900\"\n")
    recipe = prep.suggest_recipe(prep.profile(p))
    ops = {op["op"] for op in recipe["ops"]}
    assert "coerce" in ops
    coerce_op = next(op for op in recipe["ops"] if op["op"] == "coerce")
    assert coerce_op["column"] == "amount"
    assert "reason" in coerce_op


def test_suggest_recipe_proposes_dedupe_when_duplicates_present(tmp_path):
    p = tmp_path / "dupes.csv"
    p.write_text("a,b\n1,2\n1,2\n3,4\n")
    recipe = prep.suggest_recipe(prep.profile(p))
    assert any(op["op"] == "dedupe" for op in recipe["ops"])


def test_suggest_recipe_renames_messy_headers(tmp_path):
    p = tmp_path / "messy.csv"
    p.write_text("Group Name,Value!\nA,1\nB,2\n")
    recipe = prep.suggest_recipe(prep.profile(p))
    rename_op = next(op for op in recipe["ops"] if op["op"] == "rename")
    assert rename_op["map"] == {"Group Name": "group_name", "Value!": "value"}


# --------------------------------------------------------------------------- #
# apply() — representative ops
# --------------------------------------------------------------------------- #

@pytest.fixture
def basic_csv(tmp_path):
    p = tmp_path / "basic.csv"
    p.write_text("Group,Value\nA,1\nA,2\nB,3\nB,4\n")
    return p


def test_apply_rename_and_drop(basic_csv, tmp_path):
    recipe = {"read": {"skiprows": 0}, "ops": [
        {"op": "rename", "map": {"Group": "group", "Value": "value"}},
        {"op": "drop", "columns": ["value"]},
    ]}
    out = tmp_path / "out.csv"
    report = prep.apply(basic_csv, recipe, out)
    assert report["columns_out"] == ["group"]
    assert out.exists()


def test_apply_coerce_numeric(tmp_path):
    p = tmp_path / "money.csv"
    p.write_text("amount\n\"$1,200\"\n\"$1,400\"\n")
    recipe = {"ops": [{"op": "coerce", "column": "amount", "to": "numeric"}]}
    report = prep.apply(p, recipe)
    assert report["steps"][0]["detail"]["n_null_after"] == 0


def test_apply_parse_date_derives_year_and_decade(tmp_path):
    p = tmp_path / "dates.csv"
    p.write_text("event_date\n1994-05-01\n2004-06-01\n")
    recipe = {"ops": [{"op": "parse_date", "column": "event_date", "derive": ["year", "decade"]}]}
    report = prep.apply(p, recipe)
    assert report["steps"][0]["detail"]["derived"] == ["year", "decade"]


def test_apply_bin_decade(tmp_path):
    p = tmp_path / "years.csv"
    p.write_text("year\n1991\n1994\n2001\n2009\n")
    recipe = {"ops": [{"op": "bin", "column": "year", "method": "decade", "name": "decade"}]}
    report = prep.apply(p, recipe, tmp_path / "out.csv")
    df = pd.read_csv(tmp_path / "out.csv")
    assert set(df["decade"]) == {"1990s", "2000s"}
    assert report["rows_out"] == 4


def test_apply_bin_median_split(tmp_path):
    p = tmp_path / "vals.csv"
    p.write_text("v\n1\n2\n3\n4\n")
    recipe = {"ops": [{"op": "bin", "column": "v", "method": "median_split", "name": "split"}]}
    prep.apply(p, recipe, tmp_path / "out.csv")
    df = pd.read_csv(tmp_path / "out.csv")
    assert df["split"].nunique() == 2


def test_apply_transform_log10_requires_positive_values(tmp_path):
    p = tmp_path / "neg.csv"
    p.write_text("v\n-1\n2\n3\n")
    recipe = {"ops": [{"op": "transform", "column": "v", "method": "log10"}]}
    with pytest.raises(prep.RecipeError, match="non-positive"):
        prep.apply(p, recipe)


def test_apply_transform_log1p_handles_zeros(tmp_path):
    p = tmp_path / "zero.csv"
    p.write_text("v\n0\n1\n9\n")
    recipe = {"ops": [{"op": "transform", "column": "v", "method": "log1p", "name": "log_v"}]}
    report = prep.apply(p, recipe, tmp_path / "out.csv")
    df = pd.read_csv(tmp_path / "out.csv")
    assert df["log_v"].iloc[0] == pytest.approx(0.0)
    assert report["steps"][0]["detail"]["method"] == "log1p"


def test_apply_filter_keeps_matching_rows(basic_csv):
    recipe = {"ops": [{"op": "filter", "column": "Value", "cmp": ">", "value": 2}]}
    report = prep.apply(basic_csv, recipe)
    assert report["rows_out"] == 2
    assert report["steps"][0]["detail"]["removed"] == 2


def test_apply_dropna_removes_missing_rows(tmp_path):
    p = tmp_path / "missing.csv"
    p.write_text("a,b\n1,2\n,4\n5,\n")
    recipe = {"ops": [{"op": "dropna"}]}
    report = prep.apply(p, recipe)
    assert report["rows_out"] == 1


def test_apply_fillna_with_explicit_value(tmp_path):
    p = tmp_path / "missing.csv"
    # a fully blank line is dropped by pandas outright; use a second column so
    # the row survives with a real missing value in "a".
    p.write_text("a,b\n1,x\n,y\n3,z\n")
    recipe = {"ops": [{"op": "fillna", "column": "a", "value": 0}]}
    report = prep.apply(p, recipe, tmp_path / "out.csv")
    df = pd.read_csv(tmp_path / "out.csv")
    assert df["a"].tolist() == [1, 0, 3]
    assert report["steps"][0]["detail"]["column"] == "a"


def test_apply_dedupe_removes_exact_duplicates(tmp_path):
    p = tmp_path / "dupes.csv"
    p.write_text("a,b\n1,2\n1,2\n3,4\n")
    recipe = {"ops": [{"op": "dedupe"}]}
    report = prep.apply(p, recipe)
    assert report["rows_out"] == 2
    assert report["steps"][0]["detail"]["removed"] == 1


def test_apply_winsorize_clips_extremes(tmp_path):
    p = tmp_path / "outliers.csv"
    values = list(range(1, 100)) + [10000]
    p.write_text("v\n" + "\n".join(str(v) for v in values) + "\n")
    recipe = {"ops": [{"op": "winsorize", "column": "v", "limits": [0.01, 0.01]}]}
    prep.apply(p, recipe, tmp_path / "out.csv")
    df = pd.read_csv(tmp_path / "out.csv")
    assert df["v"].max() < 10000


def test_apply_date_diff_computes_duration_in_days(tmp_path):
    p = tmp_path / "durations.csv"
    p.write_text("start,end\n2020-01-01,2020-01-11\n2020-02-01,2020-02-03\n")
    recipe = {"ops": [{"op": "date_diff", "start": "start", "end": "end", "name": "duration_days"}]}
    report = prep.apply(p, recipe, tmp_path / "out.csv")
    df = pd.read_csv(tmp_path / "out.csv")
    assert df["duration_days"].tolist() == [10, 2]
    assert report["steps"][0]["detail"]["name"] == "duration_days"


def test_apply_aggregate_counts_rows_per_group(tmp_path):
    p = tmp_path / "events.csv"
    p.write_text("year\n2020\n2020\n2020\n2021\n")
    recipe = {"ops": [{"op": "aggregate", "group_by": "year", "count_name": "n"}]}
    report = prep.apply(p, recipe, tmp_path / "out.csv")
    df = pd.read_csv(tmp_path / "out.csv")
    assert df.set_index("year")["n"].to_dict() == {2020: 3, 2021: 1}
    assert report["rows_out"] == 2


def test_apply_unknown_op_raises_recipe_error(basic_csv):
    with pytest.raises(prep.RecipeError, match="unknown op"):
        prep.apply(basic_csv, {"ops": [{"op": "not_a_real_op"}]})


def test_apply_never_touches_the_source_file(basic_csv):
    original = basic_csv.read_text()
    prep.apply(basic_csv, {"ops": [{"op": "drop", "columns": ["Value"]}]},
               basic_csv.parent / "out.csv")
    assert basic_csv.read_text() == original


# --------------------------------------------------------------------------- #
# CLI: python -m stat_board.prep {profile|suggest|apply|auto}
# --------------------------------------------------------------------------- #

def test_cli_profile(basic_csv, capsys):
    code = prep.main(["profile", "--data", str(basic_csv)])
    assert code == 0
    out = json.loads(capsys.readouterr().out)
    assert out["n_rows"] == 4


def test_cli_suggest(tmp_path, capsys):
    p = tmp_path / "dupes.csv"
    p.write_text("a,b\n1,2\n1,2\n3,4\n")
    code = prep.main(["suggest", "--data", str(p)])
    assert code == 0
    out = json.loads(capsys.readouterr().out)
    assert any(op["op"] == "dedupe" for op in out["ops"])


def test_cli_apply(basic_csv, tmp_path, capsys):
    recipe_path = tmp_path / "recipe.json"
    recipe_path.write_text(json.dumps({"ops": [{"op": "rename", "map": {"Group": "group"}}]}))
    out_path = tmp_path / "clean.csv"
    code = prep.main(["apply", "--data", str(basic_csv), "--recipe", str(recipe_path),
                       "--out", str(out_path)])
    assert code == 0
    assert out_path.exists()
    out = json.loads(capsys.readouterr().out)
    assert "group" in out["columns_out"]


def test_cli_auto_writes_clean_csv_and_recipe(tmp_path, capsys):
    p = tmp_path / "dupes.csv"
    p.write_text("a,b\n1,2\n1,2\n3,4\n")
    out_path = tmp_path / "clean.csv"
    code = prep.main(["auto", "--data", str(p), "--out", str(out_path)])
    assert code == 0
    out = json.loads(capsys.readouterr().out)
    assert out_path.exists()
    assert out["recipe_saved"] == str(out_path.with_suffix(".recipe.json"))
    assert out_path.with_suffix(".recipe.json").exists()


def test_cli_bad_recipe_exits_two_with_json_error(basic_csv, tmp_path, capsys):
    recipe_path = tmp_path / "bad.json"
    recipe_path.write_text(json.dumps({"ops": [{"op": "not_a_real_op"}]}))
    code = prep.main(["apply", "--data", str(basic_csv), "--recipe", str(recipe_path),
                       "--out", str(tmp_path / "out.csv")])
    assert code == 2
    err = json.loads(capsys.readouterr().err)
    assert err["error"] == "RecipeError"
